remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: Rashika Dabas
description: Welcome to my dataland! Laddoo welcomes you to this page! Grab a cup of tea and please browse through the projects that are of interest to you!  
show_downloads: false
google_analytics: true
theme: jekyll-theme-architect
